#!/usr/bin/env python3
"""Regenerate src/seccomp/tables.rs, the syscall name to number tables.

Numbers come from two sources, merged with the kernel headers winning:

  * /usr/include/asm/unistd_{64,32,x32}.h on an x86_64 build host, which is
    authoritative for the three x86 architectures and includes the obsolete
    entries that real seccomp profiles still name.
  * hrw/syscalls-table, for aarch64 and arm, which a single build host cannot
    provide headers for.

Run with the fetched tables in the working directory:

    ./gen-syscall-tables.py tbl-x86_64.txt tbl-i386.txt tbl-x32.txt \
        tbl-arm64.txt tbl-arm.txt > ../src/seccomp/tables.rs
"""

import re
import sys

ARCHES = [
    # Source name, Rust constant, documentation name.
    ("x86_64", "X86_64", "x86-64"),
    ("i386", "X86", "i386"),
    ("x32", "X32", "x32"),
    ("arm64", "AARCH64", "aarch64"),
    ("arm", "ARM", "arm (EABI)"),
]
HEADERS = {
    "x86_64": "/usr/include/asm/unistd_64.h",
    "i386": "/usr/include/asm/unistd_32.h",
    "x32": "/usr/include/asm/unistd_x32.h",
}
X32_BIT = 0x40000000


def read_table(path):
    out = {}
    with open(path) as fh:
        for line in fh:
            parts = line.rstrip("\n").split("\t")
            if len(parts) >= 2 and parts[1].strip():
                out[parts[0]] = int(parts[1])
    return out


def read_header(path, x32):
    out = {}
    pattern = re.compile(r"^#define __NR_(\w+)\s+(\d+)")
    try:
        fh = open(path)
    except OSError:
        return out
    with fh:
        for line in fh:
            m = pattern.match(line)
            if m:
                value = int(m.group(2))
                out[m.group(1)] = value | X32_BIT if x32 else value
    return out


def rust_int(value):
    """Formats an integer the way rustfmt and clippy both want it."""
    if -9999 <= value <= 9999:
        return str(value)
    sign = "-" if value < 0 else ""
    digits = str(abs(value))
    groups = []
    while len(digits) > 3:
        groups.insert(0, digits[-3:])
        digits = digits[:-3]
    groups.insert(0, digits)
    return sign + "_".join(groups)


def main(argv):
    if len(argv) != len(ARCHES) + 1:
        sys.exit(__doc__)

    numbers = {
        arch: read_table(path)
        for (arch, _, _), path in zip(ARCHES, argv[1:])
    }
    for arch, path in HEADERS.items():
        from_header = read_header(path, arch == "x32")
        if from_header:
            numbers[arch].update(from_header)

    names = sorted({n for table in numbers.values() for n in table})

    print("//! Syscall name to number tables, one column per architecture.")
    print("//!")
    print("//! Generated by `tools/gen-syscall-tables.py`. Do not edit by")
    print("//! hand: regenerate instead, so that every architecture stays in")
    print("//! step with the same kernel release.")
    print("//!")
    print("//! `NAMES` is sorted, so a name resolves by binary search and then")
    print("//! indexes every per-architecture column at the same position. A")
    print("//! column entry of `ABSENT` means the architecture does not")
    print("//! implement that call, which a profile may legitimately name.")
    print()
    print("/// A syscall the architecture does not implement.")
    print("pub const ABSENT: i32 = -1;")
    print()
    print("/// Number of syscalls the tables cover.")
    print(f"pub const COUNT: usize = {len(names)};")
    print()
    print("/// Every syscall name, sorted, shared by all architectures.")
    print(f"pub static NAMES: [&str; COUNT] = [")
    for i in range(0, len(names), 4):
        row = ", ".join(f'"{n}"' for n in names[i : i + 4])
        print(f"    {row},")
    print("];")

    for arch, const, human in ARCHES:
        print()
        print(f"/// Syscall numbers for {human}.")
        print(f"pub static {const}: [i32; COUNT] = [")
        values = [numbers[arch].get(n, -1) for n in names]
        for i in range(0, len(values), 12):
            row = ", ".join(rust_int(v) for v in values[i : i + 12])
            print(f"    {row},")
        print("];")


if __name__ == "__main__":
    main(sys.argv)
